brew "git"
brew "starship"
brew "eza"
brew "uv"
brew "zsh-autosuggestions"
brew "fzf"
brew "zoxide"
brew "stow"
brew "bat"

cask "ghostty"
cask "visual-studio-code"
cask "font-moralerspace-hw"
cask "font-udev-gothic-nf"
cask "font-cica"
cask "openineditor-lite"
cask "openinterminal-lite"
